Simple instructions
reactorlabs/rir pull request #270
Opened 2018-11-25 17:48 UTC by Jakobeha

This PR allows you to add a new "simple" instruction easier. A "simple" instruction compiles to a single assembly instruction handled in interp.cpp - currently the only "simple" instructions are int3 and printInvocation. Instead of changing multiple files, just declare the instruction in [simple_instruction_list.h](https://github.com/Jakobeha/rir/blob/simple_instr/rir/src/simple_instruction_list.h), and then define it in interp.cpp. simple_instruction_list.h uses "recursive" preprocessor macros like instruction_list.h.

This PR includes my other PR, which adds the printInvocation instruction.

The program should behave almost the same as my previous PR, **except** instead of creating breakpoints in R with `.debug.break()`, you need to write `.int3()`. This makes the naming easier, since ".debug.break()" adds an "int3" instruction. It could be fixed by adding a new field to the definitions in simple_instruction_list.h, or renaming "int3" to "debugBreak".

This PR also fixes #249 with a new file, symbol_list.h. symbol_list.h uses preprocessor macros like instruction_list.h and simple_instruction_list.h, and it's used by Symbols.h and Symbols.cpp.

2018-11-26 18:57 UTC, mhyee commented
Thanks for working on this! I'm going to look at it later this week when I have more time, but I have two quick comments for now:

1. There's some issue with the file permissions. If you look at the diff on GitHub, all the files had their permissions changed from 644 to 755, including a lot of unrelated files. Could you fix this?

2. There are some merge conflicts, because the codebase was updated while you were making changes. This means our continuous integration tests can't run, and we wouldn't be able to merge in the changes. Could you please resolve the merge conflicts and update your branch?

2018-11-27 02:54 UTC, mhyee commented
Sorry, but it looks like there's still some merge conflicts.

Also, some of the permissions you changed to 644 should actually be 755. This is why the Travis CI build is broken.

2018-11-30 19:12 UTC, mhyee requested changes
Thanks for making the changes, and thanks for your patience.

I left a few small comments in the PR, but I also have two larger comments here.

First, I'm not sure why the build is failing. [cppcheck is complaining](https://travis-ci.org/reactorlabs/rir/jobs/460463334) about some code style, for [a file that you didn't change](https://github.com/reactorlabs/rir/blob/master/rir/src/compiler/pir/tag.cpp). (@o-, any thoughts?)

We'll probably have to add a suppression (refer to the [cppcheck manual, chapter 9](http://cppcheck.sourceforge.net/manual.pdf)). For RIR, we've been using a combination of inline suppressions and command-line suppressions in our [cppcheck script](https://github.com/reactorlabs/rir/blob/master/tools/cppcheck), so pick whichever you think is more appropriate.

Second, I wonder if there are other redundant instructions you could factor out? Right now, the PR makes `int3` and `printInvocation` simple instructions, but we still haven't decided if we want to keep `printInvocation`. So the changes here have factored out the code for one, maybe two, instructions, and adding a new instruction (simple or otherwise) is pretty rare. (Another thing you could look at is the diff: as a *very* loose rule of thumb, a refactor that adds more code than it removes might not be worth it.)

Maybe it makes more sense to do the refactoring for individual file? e.g., `BC.cpp`, `BC.h`, and `BC_inc.h` have a lot of "trivial" code.

Please take a look and let me know what you think. If it doesn't seem worthwhile, the symbols refactoring is still worthwhile and something we could merge in.

2018-11-30 19:12 UTC, mhyee commented on rir/src/compiler/pir/instruction_list.h
> +#define BINOP_INSTRUCTIONS(V)                                                  \
Why was this duplicated?

2018-11-30 19:12 UTC, mhyee commented on rir/src/runtime/Function.cpp
> +
Unnecessary change.

2018-11-30 19:12 UTC, mhyee commented on rir/src/R/Symbols.cpp
>  } // namespace rjit
Since you're already updating this file, could you update the comment to `// namespace rir`?

2018-11-30 19:12 UTC, mhyee commented on rir/src/R/Symbols.h
>  } // namespace rjit
Same with this comment. `rjit` -> `rir`.

2018-12-11 19:56 UTC, Jakobeha commented
Hello,

Sorry this took so long, I've been busy with finals and adjusting for winter break, so I haven't worked on this until very recently.

I applied all of the changes you requested:
- Small changes [556df88]
- I also found out what was giving cppcheck an issue, I didn't need to actually suppress anything, I just needed to fix an import path to `simple_instruction_list.h` (for future reference: cppcheck wanted `../../simple_instruction_list.h` for one of the files, every other one works with just `simple_instruction_list.h`) [0f2f232]
- Lastly, I abstracted all of the `BC` constructors which take no arguments and don't do anything, in `BC.cpp`, `BC.h`, and `BC_inc.h` (e.g. `inline static BC <name>();`). Now, you just need to add an entry to `BC_noarg_list.h` instead of changing those 3 files. [1f7feb3]

2018-12-19 19:02 UTC, mhyee approved these changes

2018-12-19 19:05 UTC, mhyee commented
Thanks for the update, and no worries about being slow. I should also apologize for being busy on my end.

Good catch with the cppcheck issue, and thanks for summarizing your commits!

This is good to merge, except that there's still a minor conflict, which is why the tests are failing. @o- and I thought there would be a clean merge, but `identical_` was renamed to `identical_noforce_` in a257d538febf74751ecf675223c25332ef270614, and the merge commit messed things up a bit.

Once you resolve this and all the tests pass, I'll merge it in.

2019-01-10 16:47 UTC, merged